on: push

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: LS
      run : ls -la
    
    - name: Prepare project
      run : |
        cd Углубленный_C_C++/Homework_1/
        pwd
        ls -la
        script