on: push

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: LS
      run : ls -la
    
    - name: Prepare project
      run : |
        cd Углубленный_C_C++/Homework_1/
        pwd
        ls -la
        sudo apt update -y
        sudo apt install -y cppcheck clang-tidy python3-pip libc6-dbg cmake libgtest-dev
        sudo pip install cpplint
        rm -rf build
        mkdir build
        cd build
        cmake ..
        cmake --build .
        cd ..
        build/tests/test_fib